// Contract ABI (Interface). This should match the ABI generated by your Solidity contract
const codingTokenAbi = [
    // ABI of the CodingToken contract with methods you want to call
    {
        "inputs": [],
        "name": "getInternships",
        "outputs": [
            {
                "components": [
                    { "internalType": "string", "name": "title", "type": "string" },
                    { "internalType": "uint256", "name": "tokenCost", "type": "uint256" },
                    { "internalType": "bool", "name": "isUnlocked", "type": "bool" }
                ],
                "internalType": "struct CodingToken.Internship[]",
                "name": "",
                "type": "tuple[]"
            }
        ],
        "stateMutability": "view",
        "type": "function"
    },
    {
        "inputs": [],
        "name": "getProblems",
        "outputs": [
            {
                "components": [
                    { "internalType": "string", "name": "title", "type": "string" },
                    { "internalType": "uint256", "name": "tokenReward", "type": "uint256" },
                    { "internalType": "bool", "name": "isSolved", "type": "bool" }
                ],
                "internalType": "struct CodingToken.Problem[]",
                "name": "",
                "type": "tuple[]"
            }
        ],
        "stateMutability": "view",
        "type": "function"
    },
    {
        "inputs": [{ "internalType": "uint256", "name": "problemIndex", "type": "uint256" }],
        "name": "solveProblem",
        "outputs": [],
        "stateMutability": "nonpayable",
        "type": "function"
    },
    {
        "inputs": [{ "internalType": "uint256", "name": "internshipIndex", "type": "uint256" }],
        "name": "unlockInternship",
        "outputs": [],
        "stateMutability": "nonpayable",
        "type": "function"
    }
];

// Replace with your contract's deployed address
const contractAddress = "0x7839a35B8ED36f753C9DA26e6aa23A6355FCee60";

// Connect to Ethereum provider using MetaMask
let provider;
let signer;
let contract;

document.getElementById('connectWallet').addEventListener('click', async () => {
    if (typeof window.ethereum !== 'undefined') {
        await ethereum.request({ method: 'eth_requestAccounts' });
        provider = new ethers.providers.Web3Provider(window.ethereum);
        signer = provider.getSigner();
        const account = await signer.getAddress();
        document.getElementById('accountInfo').innerText = `Connected: ${account}`;
        
        contract = new ethers.Contract(contractAddress, codingTokenAbi, signer);

        loadProblems();
        loadInternships();
    } else {
        alert('Please install MetaMask!');
    }
});

// Function to load problem statements from the contract
async function loadProblems() {
    const problemList = document.getElementById('problemList');
    problemList.innerHTML = '';
    try {
        const problems = await contract.getProblems();
        problems.forEach((problem, index) => {
            problemList.innerHTML += `<p>Problem ${index + 1}: ${problem.title}, Reward: ${ethers.utils.formatUnits(problem.tokenReward, 18)} tokens, Solved: ${problem.isSolved}</p>`;
        });
    } catch (error) {
        console.error('Error fetching problems:', error);
    }
}

// Function to load internships from the contract
async function loadInternships() {
    const internshipList = document.getElementById('internshipList');
    internshipList.innerHTML = '';
    try {
        const internships = await contract.getInternships();
        internships.forEach((internship, index) => {
            internshipList.innerHTML += `<p>Internship ${index + 1}: ${internship.title}, Cost: ${ethers.utils.formatUnits(internship.tokenCost, 18)} tokens, Unlocked: ${internship.isUnlocked}</p>`;
        });
    } catch (error) {
        console.error('Error fetching internships:', error);
    }
}

// Solve problem function
async function solveProblem() {
    const problemIndex = document.getElementById('problemIndex').value;
    try {
        const tx = await contract.solveProblem(problemIndex);
        await tx.wait();
        alert('Problem solved!');
        loadProblems();
    } catch (error) {
        console.error('Error solving problem:', error);
    }
}

// Unlock internship function
async function unlockInternship() {
    const internshipIndex = document.getElementById('internshipIndex').value;
    try {
        const tx = await contract.unlockInternship(internshipIndex);
        await tx.wait();
        alert('Internship unlocked!');
        loadInternships();
    } catch (error) {
        console.error('Error unlocking internship:', error);
    }
}
